### ISSUE TITLE
Scrollbars block data in plots

### ISSUE THREAD

**Issue by justinshenk** [ModelOriented/pyCeterisParibus#23]
**Describe the bug**
Scroll bars block the data in plots:

**To Reproduce**
Run code from README tutorial.

**Expected behavior**
Expected to be able to read data behind scroll bar, but can't.

**Screenshots**
![image](https://user-images.githubusercontent.com/10270308/56275400-ec11e200-6100-11e9-8b10-010e3a153135.png)

**Desktop (please complete the following information):**
Mac OSX, Chrome

**Comment by kmichael08** [comment]
@flaminka Can you have a look at it?

**Comment by flaminka** [comment]
Hi, thank you for reporting this! :) Unfortunately, I cannot reproduce this error, I've evoked this code on Windows 10  and also on Mac Mojave, in Chrome and everything seems to work. Could you please define which version of Chrome you use? And, if possible, make a screen recording when you evoke this code / make printscreens of Chrome console and Python console?

**Comment by justinshenk** [comment]
This issue happens on Chrome 73.0. It is fixed by opening and closing the development tools window. Closing this issue since it seems specific to my computer.
